dist: trusty
language: node_js

node_js:
  - "8"
  - "6"
os:
  - linux

addons:
  firefox: latest
  chrome: stable

before_install: yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update ;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

after_script: greenkeeper-lockfile-upload

cache:
  yarn: true
